// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTktQQf6z1witAcwQlT2QQjzC8j68QHxs',
    appId: '1:393155976013:web:c0b81a7417aa289b857504',
    messagingSenderId: '393155976013',
    projectId: 'pettodo-6bab8',
    authDomain: 'pettodo-6bab8.firebaseapp.com',
    storageBucket: 'pettodo-6bab8.firebasestorage.app',
    measurementId: 'G-R44Z2T48ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIEXb0p7Id87EyqGtgKt09b-aKlMw2-fs',
    appId: '1:393155976013:android:4cc8ba0a3794064b857504',
    messagingSenderId: '393155976013',
    projectId: 'pettodo-6bab8',
    storageBucket: 'pettodo-6bab8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_sNIjF6jJyZIwkTtTnngIXYUoMINE6c',
    appId: '1:393155976013:ios:c4757375faa2f301857504',
    messagingSenderId: '393155976013',
    projectId: 'pettodo-6bab8',
    storageBucket: 'pettodo-6bab8.firebasestorage.app',
    androidClientId: '393155976013-r58rpqp01pk0c5p7tmt5u7furpprh6pu.apps.googleusercontent.com',
    iosClientId: '393155976013-s2qu6d1i0fpfnj3fjsst6gpno646s074.apps.googleusercontent.com',
    iosBundleId: 'com.example.pettodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6_sNIjF6jJyZIwkTtTnngIXYUoMINE6c',
    appId: '1:393155976013:ios:c4757375faa2f301857504',
    messagingSenderId: '393155976013',
    projectId: 'pettodo-6bab8',
    storageBucket: 'pettodo-6bab8.firebasestorage.app',
    androidClientId: '393155976013-r58rpqp01pk0c5p7tmt5u7furpprh6pu.apps.googleusercontent.com',
    iosClientId: '393155976013-s2qu6d1i0fpfnj3fjsst6gpno646s074.apps.googleusercontent.com',
    iosBundleId: 'com.example.pettodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlhRh3TZXJBy5OzZEBVeIBRYZtAgFpB7c',
    appId: '1:393155976013:web:645f609de49df2ed857504',
    messagingSenderId: '393155976013',
    projectId: 'pettodo-6bab8',
    authDomain: 'pettodo-6bab8.firebaseapp.com',
    storageBucket: 'pettodo-6bab8.firebasestorage.app',
    measurementId: 'G-TW4520W6B1',
  );

}